services:
  app:
    build: .
    environment:
      - DATABASE_URL="postgresql://postgres:muhammad571@localhost:5432/lingostep_project?schema=public"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
